export const GERMAN_LEVELS = ["Letters", "Numbers", "Words", "A1", "A2", "B1", "B2", "C1", "C2"] as const;
export type GermanLevel = (typeof GERMAN_LEVELS)[number];

export interface Exercise {
  phrase: string;
  translation: string;
  level: GermanLevel;
  imageUrl?: string;
}

export const EXERCISES: Exercise[] = [
  // Letters
  { phrase: "A", translation: "The letter A", level: "Letters" },
  { phrase: "B", translation: "The letter B", level: "Letters" },
  { phrase: "C", translation: "The letter C", level: "Letters" },
  { phrase: "D", translation: "The letter D", level: "Letters" },
  { phrase: "E", translation: "The letter E", level: "Letters" },
  { phrase: "F", translation: "The letter F", level: "Letters" },
  { phrase: "G", translation: "The letter G", level: "Letters" },
  { phrase: "H", translation: "The letter H", level: "Letters" },
  { phrase: "I", translation: "The letter I", level: "Letters" },
  { phrase: "J", translation: "The letter J", level: "Letters" },
  { phrase: "K", translation: "The letter K", level: "Letters" },
  { phrase: "L", translation: "The letter L", level: "Letters" },
  { phrase: "M", translation: "The letter M", level: "Letters" },
  { phrase: "N", translation: "The letter N", level: "Letters" },
  { phrase: "O", translation: "The letter O", level: "Letters" },
  { phrase: "P", translation: "The letter P", level: "Letters" },
  { phrase: "Q", translation: "The letter Q", level: "Letters" },
  { phrase: "R", translation: "The letter R", level: "Letters" },
  { phrase: "S", translation: "The letter S", level: "Letters" },
  { phrase: "T", translation: "The letter T", level: "Letters" },
  { phrase: "U", translation: "The letter U", level: "Letters" },
  { phrase: "V", translation: "The letter V", level: "Letters" },
  { phrase: "W", translation: "The letter W", level: "Letters" },
  { phrase: "X", translation: "The letter X", level: "Letters" },
  { phrase: "Y", translation: "The letter Y", level: "Letters" },
  { phrase: "Z", translation: "The letter Z", level: "Letters" },
  { phrase: "Ä", translation: "The letter Ä", level: "Letters" },
  { phrase: "Ö", translation: "The letter Ö", level: "Letters" },
  { phrase: "Ü", translation: "The letter Ü", level: "Letters" },
  { phrase: "ß", translation: "The letter ß (Eszett)", level: "Letters" },

  // Numbers
  { phrase: "Null", translation: "Zero (0)", level: "Numbers" },
  { phrase: "Eins", translation: "One (1)", level: "Numbers" },
  { phrase: "Zwei", translation: "Two (2)", level: "Numbers" },
  { phrase: "Drei", translation: "Three (3)", level: "Numbers" },
  { phrase: "Vier", translation: "Four (4)", level: "Numbers" },
  { phrase: "Fünf", translation: "Five (5)", level: "Numbers" },
  { phrase: "Sechs", translation: "Six (6)", level: "Numbers" },
  { phrase: "Sieben", translation: "Seven (7)", level: "Numbers" },
  { phrase: "Acht", translation: "Eight (8)", level: "Numbers" },
  { phrase: "Neun", translation: "Nine (9)", level: "Numbers" },
  { phrase: "Zehn", translation: "Ten (10)", level: "Numbers" },
  { phrase: "Elf", translation: "Eleven (11)", level: "Numbers" },
  { phrase: "Zwölf", translation: "Twelve (12)", level: "Numbers" },
  { phrase: "Zwanzig", translation: "Twenty (20)", level: "Numbers" },
  { phrase: "Hundert", translation: "One hundred (100)", level: "Numbers" },

  // Words
  { phrase: "Hallo", translation: "Hello", level: "Words" },
  { phrase: "Tschüss", translation: "Bye", level: "Words" },
  { phrase: "Bitte", translation: "Please / You're welcome", level: "Words" },
  { phrase: "Danke", translation: "Thanks", level: "Words" },
  { phrase: "Ja", translation: "Yes", level: "Words" },
  { phrase: "Nein", translation: "No", level: "Words" },
  { phrase: "Brot", translation: "Bread", level: "Words" },
  { phrase: "Wasser", translation: "Water", level: "Words" },
  { phrase: "Haus", translation: "House", level: "Words" },
  { phrase: "Auto", translation: "Car", level: "Words" },
  { phrase: "Freund", translation: "Friend", level: "Words" },
  { phrase: "Schule", translation: "School", level: "Words" },
  { phrase: "Arbeit", translation: "Work", level: "Words" },
  { phrase: "Essen", translation: "Food / To eat", level: "Words" },
  { phrase: "Trinken", translation: "To drink", level: "Words" },

  // A1
  { phrase: "Guten Tag, wie geht es Ihnen?", translation: "Good day, how are you?", level: "A1" },
  { phrase: "Ich heiße Max und ich komme aus Berlin.", translation: "My name is Max and I come from Berlin.", level: "A1" },
  { phrase: "Wo ist der Bahnhof?", translation: "Where is the train station?", level: "A1" },
  { phrase: "Ich möchte bitte einen Kaffee bestellen.", translation: "I would like to order a coffee, please.", level: "A1" },
  { phrase: "Wie viel kostet das?", translation: "How much does that cost?", level: "A1" },
  { phrase: "Entschuldigung, ich verstehe das nicht.", translation: "Sorry, I don't understand that.", level: "A1" },
  { phrase: "Können Sie das bitte wiederholen?", translation: "Can you please repeat that?", level: "A1" },
  { phrase: "Ich suche ein Hotel in der Nähe.", translation: "I am looking for a hotel nearby.", level: "A1" },
  { phrase: "Haben Sie heute Zeit?", translation: "Do you have time today?", level: "A1" },
  { phrase: "Ich arbeite als Ingenieur.", translation: "I work as an engineer.", level: "A1" },
  { phrase: "Wo wohnen Sie?", translation: "Where do you live?", level: "A1" },
  { phrase: "Ich habe eine Reservierung.", translation: "I have a reservation.", level: "A1" },
  { phrase: "Das Wetter ist heute sehr schön.", translation: "The weather is very nice today.", level: "A1" },
  { phrase: "Ich lerne Deutsch für meinen Beruf.", translation: "I am learning German for my job.", level: "A1" },
  { phrase: "Können wir uns morgen treffen?", translation: "Can we meet tomorrow?", level: "A1" },
  { phrase: "Ich brauche Hilfe.", translation: "I need help.", level: "A1" },
  { phrase: "Vielen Dank für Ihre Unterstützung.", translation: "Thank you very much for your support.", level: "A1" },
  { phrase: "Wo kann ich Fahrkarten kaufen?", translation: "Where can I buy tickets?", level: "A1" },
  { phrase: "Ich bin müde.", translation: "I am tired.", level: "A1" },
  { phrase: "Gute Nacht!", translation: "Good night!", level: "A1" },
  { phrase: "Welche Zimmernummer hat Herr Schneider?", translation: "Which room number does Mr. Schneider have?", level: "A1", imageUrl: "GENERATE" },
  { phrase: "Herr Schneider hat Zimmer zweihundertvierundfünfzig.", translation: "Mr. Schneider has room two hundred fifty-four.", level: "A1", imageUrl: "GENERATE" },
  { phrase: "Was kostet der Pullover?", translation: "How much does the sweater cost?", level: "A1", imageUrl: "GENERATE" },
  { phrase: "Der Pullover kostet dreißig Euro.", translation: "The sweater costs thirty Euro.", level: "A1", imageUrl: "GENERATE" },
  { phrase: "Der Pullover kostet neunzehn Euro fünfundneunzig.", translation: "The sweater costs nineteen Euro ninety-five.", level: "A1", imageUrl: "GENERATE" },
  { phrase: "Wie spät ist es?", translation: "What time is it?", level: "A1", imageUrl: "GENERATE" },
  { phrase: "Es ist jetzt fünfzehn Uhr.", translation: "It is now three o'clock (15:00).", level: "A1", imageUrl: "GENERATE" },
  { phrase: "Es ist gleich fünf Uhr.", translation: "It is almost five o'clock.", level: "A1", imageUrl: "GENERATE" },
  { phrase: "Es ist halb fünf.", translation: "It is half past four.", level: "A1", imageUrl: "GENERATE" },
  { phrase: "Was isst die Frau im Restaurant?", translation: "What is the woman eating in the restaurant?", level: "A1", imageUrl: "GENERATE" },
  { phrase: "Sie isst Fisch mit Pommes.", translation: "She is eating fish with fries.", level: "A1", imageUrl: "GENERATE" },
  { phrase: "Ich möchte eine Wurst bestellen.", translation: "I would like to order a sausage.", level: "A1", imageUrl: "GENERATE" },
  { phrase: "Haben Sie auch vegetarisches Essen?", translation: "Do you also have vegetarian food?", level: "A1" },
  { phrase: "Die Rechnung bitte.", translation: "The bill, please.", level: "A1" },
  { phrase: "Wo ist die Toilette?", translation: "Where is the toilet?", level: "A1" },
  { phrase: "Ich suche den Bahnhof.", translation: "I am looking for the train station.", level: "A1" },
  { phrase: "Fährt dieser Bus zum Stadtzentrum?", translation: "Does this bus go to the city center?", level: "A1" },
  { phrase: "Einmal nach Berlin, bitte.", translation: "One ticket to Berlin, please.", level: "A1" },
  { phrase: "Wann kommt der nächste Zug?", translation: "When does the next train come?", level: "A1" },
  { phrase: "Ich habe eine Frage.", translation: "I have a question.", level: "A1" },
  { phrase: "Können Sie mir helfen?", translation: "Can you help me?", level: "A1" },
  { phrase: "Sprechen Sie Englisch?", translation: "Do you speak English?", level: "A1" },
  { phrase: "Ich lerne Deutsch.", translation: "I am learning German.", level: "A1" },
  { phrase: "Wie heißt das auf Deutsch?", translation: "What is that called in German?", level: "A1" },
  // A2
  { phrase: "Gestern bin ich mit meinen Freunden ins Kino gegangen.", translation: "Yesterday I went to the cinema with my friends.", level: "A2" },
  { phrase: "Könnten Sie mir bitte helfen, den Weg zu finden?", translation: "Could you please help me find the way?", level: "A2" },
  // B1
  { phrase: "Obwohl es regnete, haben wir einen langen Spaziergang gemacht.", translation: "Although it was raining, we took a long walk.", level: "B1" },
  { phrase: "Ich interessiere mich sehr für die deutsche Kultur und Geschichte.", translation: "I am very interested in German culture and history.", level: "B1" },
  // B2
  { phrase: "Es ist von großer Bedeutung, dass wir nachhaltige Lösungen für den Umweltschutz finden.", translation: "It is of great importance that we find sustainable solutions for environmental protection.", level: "B2" },
  { phrase: "In Anbetracht der aktuellen Situation sollten wir unsere Strategie überdenken.", translation: "In view of the current situation, we should rethink our strategy.", level: "B2" },
  // C1
  { phrase: "Die Komplexität der deutschen Grammatik stellt für viele Lernende eine erhebliche Herausforderung dar.", translation: "The complexity of German grammar represents a significant challenge for many learners.", level: "C1" },
  { phrase: "Es lässt sich nicht leugnen, dass die Globalisierung sowohl Chancen als auch Risiken birgt.", translation: "It cannot be denied that globalization carries both opportunities and risks.", level: "C1" },
  // C2
  { phrase: "Die subtilen Nuancen der Sprache zu beherrschen, erfordert jahrelange, intensive Auseinandersetzung mit der Materie.", translation: "Mastering the subtle nuances of the language requires years of intensive engagement with the subject matter.", level: "C2" },
  { phrase: "Inwiefern die Digitalisierung die zwischenmenschliche Kommunikation grundlegend transformiert hat, bleibt Gegenstand lebhafter Debatten.", translation: "To what extent digitalization has fundamentally transformed interpersonal communication remains a subject of lively debate.", level: "C2" },
];
